### PR TITLE
fix: fetch new itunes subdomain

### PR DESCRIPTION
**Pull request by Iksxsuzil**
Fetch itunes url for cover and autoselect.

### CODE REVIEW

**Comment by SavageCore** [comment]
Thanks again

**Comment by Iksxsuzil** [comment]
Np, sorry for separate PR.

**Comment by SavageCore** [comment]
@all-contributors please add @ghost for code

**Comment by SavageCore** [comment]
@all-contributors please add @Iksxsuzil for code

**Pull request merged**
